#
# Makefile for the Linux kernel device drivers.
#
# 15 Sep 2000, Christoph Hellwig <hch@infradead.org>
# Rewritten to use lists instead of if-statements.
#

subdir-ccflags-y += -Werror

obj-y				+= student/
obj-y				+= dog/
obj-y				+= class/
